### ISSUE TITLE
您好 我按照您的步骤配置 不行阿

### ISSUE THREAD

**Issue by Javency** [aotianwinter/my-auto-deploy#1]
文件查找失败：'dns' at node_modules\ssh2\lib\client.js:3

**Comment by aotianwinter** [comment]
确保node及依赖模块正确安装，建议清空node_modules文件夹，重新执行npm i。还是不行请附上完整截图，或留下联系方式。

**Comment by goddlts** [comment]
@aotianwinter 是不是 uploadFile.js 中的 const ssh = new node_ssh() 对象是新创建的，而不是连接成功的那个 ssh 对象，所以连接失败，把上传的代码移动到 ssh.js 中是 ok 的

**Comment by aotianwinter** [comment]
@goddlts 你好，这里分开实现来连接、上传是为了解耦，测试发现uploadFile.js 中ssh对象是保存有连接信息的，应该为单例模式，不会影响后续上传等操作。
请问您使用时不做修改，会提示连接失败吗，能发一下截图信息吗？

**Comment by goddlts** [comment]
@aotianwinter 你好，看了 node-ssh 的源码，并没有使用单例。问题的原因是你在模块中定义 ssh 变量的时候 `ssh = new node_ssh()` 没有使用 const 或者 let，此时 ssh 变量是全局的 在 global 中，而我定义变量的时候使用了 const，是局部变量，我的局部变量是没有配置信息的。建议你的代码中都加上 const/let 定义常量/变量，否则给别人造成困惑。好几个人都遇到这样的问题了哈

**Comment by aotianwinter** [comment]
嗯，感谢指证。我下个版本更新下该问题。
