### ISSUE TITLE
已经装好ssh，运行后可以连接上服务，但是上传文件的时候失败了。

### ISSUE THREAD

**Issue by JasonYadi** [aotianwinter/my-auto-deploy#3]
![image](https://user-images.githubusercontent.com/24763020/72702315-3b53da00-3b8d-11ea-8e87-04b7add926b4.png)
``` js
const config = [
  {
    name: '项目A-dev',
    ssh: {
      host: '***.***.***.***',
      username: '***',
      password: '******'
    },
    targetDir: 'Q:/jason/study/z-yadi', // 目标压缩目录(可使用相对地址)
    targetFile: 'dist.zip', // 目标文件
    openCompress: true, // 是否开启本地压缩
    openBackUp: true, // 是否开启远端备份
    deployDir: '/wwwroot/node_test' + '/', // 远端目录
    releaseDir: '/wwwroot/web' // 发布目录
  }
]
```
发生错误:ϵͳ�Ҳ���ָ����·����
(node:36080) UnhandledPromiseRejectionWarning: undefined
(node:36080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
5-文件上传完成
unzip dist.zip
{"code":1,"stdout":"","stderr":"ϵͳ�Ҳ���ָ����·����"}
发生错误:ϵͳ�Ҳ���ָ����·����
(node:36080) UnhandledPromiseRejectionWarning: undefined
(node:36080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by aotianwinter** [comment]
你好，发布目录直接改为 web，则表示/wwwroot/node_test/下的web目录，可以尝试修改

**Comment by JasonYadi** [comment]
![微信图片_20200120141457](https://user-images.githubusercontent.com/24763020/72702969-532c5d80-3b8f-11ea-9899-c9c1409a7d3e.png)

修改后还是不行，不知道是不是node_ssh 配置的问题，我这边查了下还是没啥头绪。
{"code":1,"stdout":"","stderr":"ϵͳ�Ҳ���ָ����·����"}
发生错误:ϵͳ�Ҳ���ָ����·����
(node:39732) UnhandledPromiseRejectionWarning: undefined
(node:39732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This               error originated either by throwing inside of an async function without a catch               block, or by rejecting a promise which was not handled with .catch(). (rejectio              n id: 1)
(node:39732) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr              ecated. In the future, promise rejections that are not handled will terminate th              e Node.js process with a non-zero exit code.
5-文件上传完成
unzip dist.zip
{"code":1,"stdout":"","stderr":"ϵͳ�Ҳ���ָ����·����"}
发生错误:ϵͳ�Ҳ���ָ����·����
(node:39732) UnhandledPromiseRejectionWarning: undefined
(node:39732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This               error originated either by throwing inside of an async function without a catch               block, or by rejecting a promise which was not handled with .catch(). (rejectio              n id: 2)

**Comment by aotianwinter** [comment]
你可以添加我的微信 aotianwinter ,前面发的截图无法查看。
